Repository Codeit-part4-team1/synamon, pull requests merged in 2024-04, with the labels that each got.

#97 Feat: 예약 현황 페이지
  src/hooks/useReservationDashboard.ts
  src/pages/mypage/reservation-dashboard/index.tsx
  src/types/reservation-dashboard/index.ts
Labels: ♻️ refactor, 💫 feat

#98 검색 기능 설정, 캐싱 refetch
  src/api/activities/index.ts
  src/components/Activities/ReviewList/ReviewList.tsx
  src/components/common/Modal/ConfirmModal.tsx
  src/components/common/Pagination/Pagination.tsx
  src/components/home/CardList.tsx
  src/components/home/CurationCardList.tsx
  src/components/home/Searchbar.tsx
  src/components/layout/MainPageLayout.tsx
  src/components/ui/dialog.tsx
  src/constants/queryKeys.ts
  src/hooks/activities/index.ts
  src/pages/activities/[id]/index.tsx
  src/pages/index.tsx
  src/pages/mypage/activities/[id]/edit/index.tsx
  src/pages/mypage/activities/create/index.tsx
  src/pages/mypage/activities/temp.tsx
  src/styles/globals.css
Labels: 🎨 UI, 💫 feat

#100 다크모드 구현
  src/components/Activities/SelectHeadcount/SelectHeadcount.tsx
  src/components/common/AuthInput/EmailInput.tsx
  src/components/common/Modal/ConfirmModal.tsx
  src/components/common/SideMenu/SideMenu.tsx
  src/components/layout/BaseLayout.tsx
  src/components/layout/MainPageLayout.tsx
  src/components/myActivity/myActivitiesCard.tsx
  src/components/ui/dialog.tsx
  src/components/ui/select.tsx
  src/pages/activities/[id]/index.tsx
  src/styles/globals.css
Labels: 🎨 UI

#102 Feat: 헤더 알림 모달 기능
  src/components/common/Modal/NotificationModal.tsx
  src/components/layout/Header.tsx
  src/hooks/useMyNotifications.ts
  src/types/myNotifications/index.ts
Labels: ♻️ refactor, 💫 feat

#103 UI: 알림모달 UI 수정
  src/components/common/Modal/NotificationModal.tsx
Labels: 🎨 UI

#99 모집 현황 페이지 예약 정보 모달 기능구현
  src/components/common/Modal/ReservationInfoModal.tsx
  src/components/common/Modal/ReservationInfoModalDetail.tsx
  src/components/myHistory/ReservationCard.tsx
  src/constants/queryKeys.ts
  src/hooks/useMyActivites.ts
  src/hooks/useMyReservations.ts
  src/pages/mypage/activities/index.tsx
  src/pages/mypage/reservation-dashboard/index.tsx
  src/pages/mypage/reservations/index.tsx
  src/types/MyActivitiesType.ts
Labels: ♻️ refactor, 💫 feat

#104 instance 개선, api 형식 수정, 로그아웃 설정, mypage/~ 로 이동 시 로그인 페이지로 이동
  src/api/auth/index.ts
  src/api/myActivities/index.ts
  src/components/common/Modal/AlertModal.tsx
  src/components/common/Modal/ProfileModal.tsx
  src/hooks/auth/index.ts
  src/hooks/useAuth.ts
  src/hooks/useMyActivites.ts
  src/hooks/useUsers.ts
  src/lib/axios.ts
  src/lib/tokenAxios.ts
  src/pages/mypage/activities/[id]/edit/index.tsx
  src/pages/mypage/activities/create/index.tsx
  src/pages/mypage/activities/index.tsx
  src/pages/mypage/index.tsx
  src/pages/mypage/reservations/index.tsx
  src/pages/signin/index.tsx
Labels: 💫 feat

#105 refactor: 버그 수정 및 리팩토링
  src/components/common/Modal/ReviewModal.tsx
  src/components/myHistory/ReservationCard.tsx
  src/hooks/useMyReservations.ts
  src/pages/mypage/reservations/index.tsx
Labels: ♻️ refactor, 🐛 bug

#106 마이페이지 정보 수정 바로 업데이트 및 이미지 초기화 설정, 쿠키 유효기간 설정, datepicker 다크모드 색 설정
  src/api/myReservations/index.ts
  src/components/common/AuthInput/CheckPasswordInput.tsx
  src/components/common/AuthInput/EmailInput.tsx
  src/components/common/Input/CheckPasswordInput.tsx
  src/components/create/BannerImageUrlField.tsx
  src/components/create/SubImageUrlsField.tsx
  src/components/layout/BaseLayout.tsx
  src/components/layout/Header.tsx
  src/components/myActivity/myActivitiesCard.tsx
  src/constants/queryKeys.ts
  src/hooks/auth/index.ts
  src/hooks/myReservaions/index.ts
  src/hooks/useMyReservations.ts
  src/hooks/useUsers.ts
  src/hooks/users/index.ts
  src/lib/axios.ts
  src/pages/_app.tsx
  src/pages/mypage/index.tsx
  src/pages/mypage/reservations/index.tsx
  src/pages/signin/index.tsx
  src/pages/signup/index.tsx
  src/styles/datePicker.css
Labels: 🎨 UI, 💫 feat

#107 UI: 예약 현황 UI 변경
  src/pages/_app.tsx
  src/pages/mypage/reservation-dashboard/index.tsx
  src/styles/react-big-calendar.css
Labels: 🎨 UI

#110 예약정보 모달 오류 해결 및 api 연결
  src/components/common/Modal/ReservationInfoModal.tsx
  src/components/common/Modal/ReservationInfoModalDetail.tsx
  src/hooks/useMyActivites.ts
Labels: ♻️ refactor, 🐛 bug

#111 UI: 예약 정보 모달 애니메이션 추가
  src/components/common/Modal/ReservationInfoModal.tsx
  src/pages/mypage/reservation-dashboard/index.tsx
  src/styles/react-big-calendar.css
  src/types/reservation-dashboard/index.ts
Labels: 🎨 UI

#112 다크모드 색상 변경
  src/components/common/Modal/NotificationModal.tsx
  src/components/common/Modal/ProfileModal.tsx
  src/components/common/Modal/ReservationInfoModal.tsx
  src/components/common/Modal/ReviewModal.tsx
  src/components/common/SideMenu/SideMenu.tsx
  src/components/create/AddressField.tsx
  src/components/layout/Footer.tsx
  src/components/layout/Header.tsx
  src/components/myHistory/ReservationCard.tsx
  src/hooks/auth/index.ts
  src/lib/axios.ts
  src/pages/mypage/reservation-dashboard/index.tsx
  src/pages/mypage/reservations/index.tsx
  src/styles/globals.css
Labels: 🎨 UI

#114 UI: 헤더 알림 UI 수정
  src/components/common/Modal/NotificationModal.tsx
  src/components/common/Modal/ReservationInfoModal.tsx
  src/components/layout/Header.tsx
Labels: 🎨 UI

#116 feat: Input 파일 삭제
  src/components/common/Input/CheckPasswordInput.tsx
  src/components/common/Input/EmailInput.tsx
  src/components/common/Input/NicknameInput.tsx
  src/components/common/Input/PasswordInput.tsx
Labels: ⚙️ chore

#119 UI: ReservationInfoModal에서 띄우는 alertModal 위치 수정
  src/components/common/Modal/ReservationInfoModalDetail.tsx
Labels: 🎨 UI

#121 Refactor: console.log삭제
  src/components/common/Modal/NotificationModal.tsx
Labels: ♻️ refactor

#124 type 변경
  src/api/activities/index.ts
  src/components/common/Pagination/Pagination.tsx
  src/components/create/AddressField.tsx
  src/components/create/SchedulesField.tsx
  src/components/create/SubImageUrlsField.tsx
  src/components/home/CategoryList.tsx
  src/components/home/Searchbar.tsx
  src/components/myActivity/myActivitiesCard.tsx
  src/components/myHistory/ReservationCard.tsx
  src/constants/schema.ts
  src/hooks/activities/index.ts
  src/pages/mypage/activities/[id]/edit/index.tsx
  src/pages/mypage/activities/create/index.tsx
  src/types/activities/index.ts
  src/types/myActivities/index.ts
  src/utils/cookie.ts
Labels: ♻️ refactor

#126 메인 페이지 최적화
  next.config.mjs
  package-lock.json
  package.json
  public/images/temp-active-preview.avif
  public/images/temp-active-preview.png
  src/components/Activities/DetailHeader/DetailHeader.tsx
  src/components/Activities/ImageList/ImageList.tsx
  src/components/Activities/ReviewList/ReviewList.tsx
  src/components/Activities/SelectHeadcount/SelectHeadcount.tsx
  src/components/common/Modal/ProfileModal.tsx
  src/components/common/Pagination/Pagination.tsx
  src/components/home/Searchbar.tsx
  src/components/layout/Footer.tsx
  src/components/layout/Header.tsx
  src/components/layout/MainPageLayout.tsx
  src/components/myHistory/ReservationCard.tsx
Labels: ♻️ refactor
