Repository Codeit-part4-team1/synamon, pull requests merged in 2024-03, with the labels that each got.

#6 Button 컴포넌트 UI 구현
  src/components/common/Button.tsx
Labels: 🎨 UI

#13 Header UI 구현
  public/images/logo-header.png
  src/components/layout/Header.tsx
Labels: 🎨 UI

#8 AuthProvider 임시 구현, axios install
  package-lock.json
  package.json
  src/contexts/AuthProvider.tsx
  src/pages/_app.tsx
  src/types/apiTypes.ts
Labels: 💫 feat

#17 feat: userCookie 객체에 빈문자열 프로퍼티 삭제
  src/contexts/AuthProvider.tsx
  src/types/apiTypes.ts
Labels: ♻️ refactor, 🐛 bug, 💫 feat

#10 Nickname input 컴포넌트 기능 구현
  src/components/common/NicknameInput.tsx
  src/contexts/AuthProvider.tsx
Labels: 💫 feat

#9 Email input 컴포넌트 기능 구현
  public/images/btn_visibility_on_24px.png
  public/images/opendEyesIcon.png
  src/components/common/EmailInput.tsx
  src/contexts/AuthProvider.tsx
Labels: 💫 feat

#11 Password input 컴포넌트 기능 구현
  src/components/common/PasswordInput.tsx
Labels: 💫 feat

#12 CheckPassword input 컴포넌트 기능 구현
  src/components/common/CheckPasswordInput.tsx
Labels: 💫 feat

#18 SignIn Page 구현 (모달 기능 구현 시, 추후수정 필요)
  src/pages/signInPage.tsx
Labels: 💫 feat

#19 SignUp Page 구현 (모달 기능 구현 시, 추후수정 필요)
  src/pages/signUp.tsx
Labels: 💫 feat

#20 Dropdown 컴포넌트 UI 구현
  package.json
  src/components/ui/select.tsx
  src/pages/index.tsx
Labels: 🎨 UI

#21 Dark Mode 구현
  package.json
  src/components/theme-provider.tsx
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: 💫 feat

#26 Pagination 컴포넌트 UI 구현 및 Button 컴포넌트 props 수정
  src/components/common/Button.tsx
  src/components/common/Pagination.tsx
  src/components/layout/Header.tsx
  src/components/ui/select.tsx
  src/pages/_app.tsx
  src/pages/index.tsx
  tailwind.config.ts
Labels: 🎨 UI

#34 feat: AlertModal 기능, UI 구현
  src/components/common/AlertModal.tsx
Labels: 🎨 UI, 💫 feat

#28 Searchbar 컴포넌트 UI 구현
  src/components/common/Searchbar.tsx
Labels: 🎨 UI

#37 layout 구현
  public/images/temp-active-preview.png
  src/components/layout/BaseLayout.tsx
  src/components/layout/MainPageLayout.tsx
  src/pages/_app.tsx
  src/pages/index.tsx
Labels: 🎨 UI

#43 메인페이지 UI 구현
  next.config.mjs
  package.json
  public/images/icon-category-culture.svg
  public/images/icon-category-food.svg
  public/images/icon-category-sightseeing.svg
  public/images/icon-category-sports.svg
  public/images/icon-category-tour.svg
  public/images/icon-category-wellbeing.svg
  src/components/common/Pagination.tsx
  src/components/home/CardList.tsx
  src/components/home/CategoryList.tsx
  src/components/home/CurationCardList.tsx
  src/components/home/Searchbar.tsx
  src/components/home/SortDropdown.tsx
  src/components/layout/Header.tsx
  src/components/layout/MainPageLayout.tsx
  src/components/ui/button.tsx
  src/components/ui/carousel.tsx
  src/pages/index.tsx
  tsconfig.json
Labels: 🎨 UI

#47 ProfileModal 컴포넌트 UI 구현
  public/images/temp-profile.png
  src/components/common/ProfileModal.tsx
Labels: 🎨 UI

#52 SideMenu UI 및 상세 페이지 레이아웃 구현
  package.json
  src/components/common/SideMenu.tsx
  src/components/home/SortDropdown.tsx
  src/components/layout/BaseLayout.tsx
  src/components/layout/Header.tsx
  src/components/layout/MenuLayout.tsx
  src/components/ui/form.tsx
  src/components/ui/input.tsx
  src/components/ui/label.tsx
  src/pages/create.tsx
Labels: 🎨 UI

#53 헤더 알림 모달 UI
  src/components/common/NotificationModal.tsx
Labels: 🎨 UI

#54 myinfo 페이지 UI
  src/pages/myInfo.tsx
Labels: 🎨 UI

#55 Alert 모달 dialog로 변경, 사용 페이지 수정
  src/components/common/AlertModal.tsx
  src/pages/myInfo.tsx
  src/pages/signIn.tsx
  src/pages/signUp.tsx
Labels: ♻️ refactor, 🎨 UI

#56 후기등록 모달 UI (수정)
  src/components/common/ReviewModal.tsx
  src/pages/_document.tsx
Labels: 🎨 UI

#57 주소 및 일정 등록 기능 구현
  package.json
  src/components/ui/dialog.tsx
  src/components/ui/input.tsx
  src/pages/create.tsx
Labels: 💫 feat

#58 예약 정보 모달 UI 구현
  package-lock.json
  package.json
  src/components/common/ReservationInfoModal.tsx
  tailwind.config.ts
Labels: 🎨 UI

#61 예약 현황 페이지 UI
  package-lock.json
  package.json
  src/pages/reservationStatus.tsx
Labels: 🎨 UI

#60 예약 내역 페이지 UI 구현
  src/components/myHistory/RESERVATIONS.ts
  src/components/myHistory/ReservationCard.tsx
  src/components/myHistory/SortDropdown.tsx
  src/pages/myHistory.tsx
  src/types/reservationTypes.ts
Labels: 🎨 UI

#62 컴포넌트 분리 및 submit 설정
  src/components/create/AddressField.tsx
  src/components/create/BannerImageUrlField.tsx
  src/components/create/CategoryField.tsx
  src/components/create/DescriptionField.tsx
  src/components/create/PriceField.tsx
  src/components/create/SchedulesField.tsx
  src/components/create/SubImageUrlsField.tsx
  src/components/create/TitleField.tsx
  src/constants/schema.ts
  src/pages/_app.tsx
  src/pages/create.tsx
Labels: 💫 feat

#65 모임 관리 페이지 UI 구현
  src/components/myGroup/GROUPS.ts
  src/components/myGroup/GroupCard.tsx
  src/pages/myGroup.tsx
  src/types/groupTypes.ts
Labels: 🎨 UI

#69 로그인, 회원가입 페이지 로고 추가, 안쓰는 아이콘 삭제
  public/images/icon-closed-eyes.png
  public/images/icon-opend-Eyes.png
  public/images/logo.png
  src/pages/signin/index.tsx
  src/pages/signup/index.tsx
Labels: 🎨 UI

#70 로그인,회원가입 페이지 UI 수정
  src/pages/signin/index.tsx
  src/pages/signup/index.tsx
Labels: 🎨 UI

#71 siginin, header, cardlist에 react query로 데이터 가져오기
  package-lock.json
  package.json
  src/components/common/Avatar/Avatar.tsx
  src/components/common/Modal/ProfileModal.tsx
  src/components/home/CardList.tsx
  src/components/layout/Header.tsx
  src/components/ui/popover.tsx
  src/hooks/useActivities.ts
  src/hooks/useAuth.ts
  src/hooks/useUsers.ts
  src/lib/axios.ts
  src/lib/network.ts
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/signin/index.tsx
  src/styles/globals.css
  src/types/auth.ts
  src/utils/cookie.ts
Labels: 💫 feat

#72 Feat: reviewList 컴포넌트 UI
  src/components/Activities/ReviewList/ReviewList.tsx
  src/lib/axios.ts
  src/pages/activities/index.tsx
  src/types/activities/activities.ts
Labels: 🎨 UI

#75 유저 정보 api 종속 쿼리 추가, 기본 프로필 사진 설정
  public/images/default-profile.png
  src/components/common/Avatar/Avatar.tsx
  src/components/home/CardList.tsx
  src/hooks/useUsers.ts
Labels: 🎨 UI, 💫 feat

#76 Feat: 회원가입 페이지 리액트 쿼리 적용
  src/components/common/Modal/AlertModal.tsx
  src/hooks/useUsers.ts
  src/pages/signup/index.tsx
  src/types/auth.ts
Labels: 💫 feat

#77 모임 이미지 url 생성 기능 구현
  next.config.mjs
  src/components/create/BannerImageUrlField.tsx
  src/components/create/SchedulesField.tsx
  src/components/create/SubImageUrlsField.tsx
  src/components/home/CardList.tsx
  src/constants/schema.ts
  src/hooks/useActivities.ts
  src/lib/axios.ts
  src/pages/_app.tsx
  src/pages/create.tsx
  src/styles/datePicker.css
Labels: 🎨 UI, 💫 feat

#81 feat: 로그아웃 기능 추가
  src/hooks/useAuth.ts
  src/utils/cookie.ts
Labels: 💫 feat

#87 mypage/activities 페이지 기능구현
  package-lock.json
  package.json
  src/components/myActivity/myActivitiesCard.tsx
  src/components/myGroup/GROUPS.ts
  src/components/myGroup/GroupCard.tsx
  src/components/ui/dropdown.tsx
  src/hooks/useMyActivites.ts
  src/pages/mypage/activities/[id]/edit/index.tsx
  src/pages/mypage/activities/index.tsx
  src/types/MyActivitiesType.ts
Labels: 🎨 UI, 💫 feat

#88 카테고리, 정렬, 페이지네이션 기능 구현
  src/api/activities/index.ts
  src/components/common/Pagination/Pagination.tsx
  src/components/home/CardList.tsx
  src/components/home/CategoryList.tsx
  src/components/home/SortDropdown.tsx
  src/constants/queryKeys.ts
  src/hooks/activities/index.ts
  src/hooks/useActivities.ts
  src/pages/index.tsx
Labels: 💫 feat

#94 Feat: Auth 페이지, 컴포넌트에 FormProvider 적용
  src/components/common/AuthInput/CheckPasswordInput.tsx
  src/components/common/AuthInput/EmailInput.tsx
  src/components/common/AuthInput/NicknameInput.tsx
  src/components/common/AuthInput/PasswordInput.tsx
  src/hooks/useAuth.ts
  src/hooks/useUsers.ts
  src/pages/mypage/index.tsx
  src/pages/signin/index.tsx
  src/pages/signup/index.tsx
  src/types/auth.ts
Labels: ♻️ refactor, 💫 feat

#91 mypage/reservations 페이지 기능 및 리뷰 모달 구현
  src/components/common/Modal/AlertModal.tsx
  src/components/common/Modal/ReviewModal.tsx
  src/components/myHistory/RESERVATIONS.ts
  src/components/myHistory/ReservationCard.tsx
  src/components/myHistory/StatusDropdown.tsx
  src/constants/queryKeys.ts
  src/hooks/useMyReservations.ts
  src/pages/mypage/reservations/index.tsx
  src/types/MyReservationTypes.ts
  src/types/common/index.ts
Labels: 🎨 UI, 💫 feat

#96 Feat: 내 정보 페이지 기능 구현
  src/hooks/useUsers.ts
  src/pages/mypage/index.tsx
  src/types/users/index.ts
Labels: ♻️ refactor, 💫 feat

#92 인기 모임 데이터 불러오기
  src/api/activities/index.ts
  src/components/Activities/DetailHeader/DetailHeader.tsx
  src/components/common/Pagination/Pagination.tsx
  src/components/create/BannerImageUrlField.tsx
  src/components/create/SubImageUrlsField.tsx
  src/components/home/CardList.tsx
  src/components/home/CategoryList.tsx
  src/components/home/CurationCardList.tsx
  src/constants/queryKeys.ts
  src/hooks/activities/index.ts
  src/hooks/useActivities.ts
  src/hooks/useMyActivites.ts
  src/hooks/useUsers.ts
  src/hooks/users/index.ts
  src/lib/axios.ts
  src/pages/activities/[id]/index.tsx
  src/pages/index.tsx
  src/pages/mypage/activities/[id]/edit/index.tsx
  src/pages/mypage/activities/create/index.tsx
  src/types/activities/index.ts
  src/utils/cookie.ts
Labels: 💫 feat
